name: danipotter
favicon: null
layout_spectrum: 0.8988916352391243
typography_spectrum: 0.307989071123302
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.031268544029444456
  lightness: 0.39596086693927646
  saturation: 0.2088713210541755
  rhythmicContrast: 0.6512946570292115
purpose: []
