name: danipotter
favicon: null
layout_spectrum: 0.92568
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1ef9f9'
    - '#000000'
    - '#434343'
    - '#868686'
    - '#d0d0d0'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
